name: Meteor Setup and Ready

# Rodar de 30 em 30 minutos
on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  setup-meteor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install curl
        run: sudo apt-get install -y curl

      - name: Install Meteor
        run: curl https://install.meteor.com | sh

      - name: Meteor Get Ready
        run: meteor --get-ready
